In [17]:
import json
import pandas as pd
import ast
import numpy as np

boun_data = pd.read_csv("data/cleaned/boun.csv")
priority_followed_data = pd.read_csv("data/cleaned/priority_followed.csv")

def safe_parse(x):
    """Safely parse stringified JSON/lists using ast.literal_eval with fallback."""
    if pd.isna(x):
        return None
    
    if isinstance(x, str):
        x = x.strip()
        if x.startswith(('[{', '[', '{', '(')):  # Detect literal structures
            try:
                return ast.literal_eval(x)
            except (ValueError, SyntaxError):
                # Fallback to string or attempt json.loads for valid JSON
                try:
                    return json.loads(x)
                except:
                    return x
    return x
    
print("Parsing BOUN data...")
for col in boun_data.columns:
    boun_data[col] = boun_data[col].map(safe_parse)

print("Parsing priority_followed data...")
for col in priority_followed_data.columns:
    priority_followed_data[col] = priority_followed_data[col].map(safe_parse)

Parsing BOUN data...
Parsing priority_followed data...

In [18]:
print(f"BOUN shape: {boun_data.shape}")
print(f"Priority followed shape: {priority_followed_data.shape}")

boun_data.columns

BOUN shape: (4608, 54)
Priority followed shape: (9946, 54)

Index(['id', 'doi', 'title', 'display_name', 'publication_year',
       'publication_date', 'ids', 'language', 'primary_location', 'type',
       'indexed_in', 'open_access', 'authorships', 'institutions',
       'countries_distinct_count', 'institutions_distinct_count',
       'corresponding_author_ids', 'corresponding_institution_ids', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_percentile', 'cited_by_percentile_year', 'biblio',
       'is_retracted', 'is_paratext', 'is_xpac', 'primary_topic', 'topics',
       'keywords', 'concepts', 'mesh', 'locations_count', 'locations',
       'best_oa_location', 'sustainable_development_goals', 'awards',
       'funders', 'has_content', 'content_urls', 'referenced_works_count',
       'referenced_works', 'related_works', 'abstract_inverted_index',
       'counts_by_year', 'updated_date', 'created_date', 'abstract_raw',
       'abstract', 'abstract_word_count', 'abstract_keywords',
       'word_frequency'],
      dtype='str')

In [19]:
boun = boun_data.copy()
priority_followed = priority_followed_data.copy()

In [20]:
boun.head()

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,...,related_works,abstract_inverted_index,counts_by_year,updated_date,created_date,abstract_raw,abstract,abstract_word_count,abstract_keywords,word_frequency
0,https://openalex.org/W7134201305,https://doi.org/10.17275/per.26.24.13.2,Investigation of Social and Cultural Informal Learning Opportunities for Middle and High School Students,Investigation of Social and Cultural Informal Learning Opportunities for Middle and High School Students,2026,2026-03-08,"{'openalex': 'https://openalex.org/W7134201305', 'doi': 'https://doi.org/10.17275/per.26.24.13.2'}",en,"{'id': 'doi:10.17275/per.26.24.13.2', 'is_oa': True, 'landing_page_url': 'https://doi.org/10.17275/per.26.24.13.2', 'pdf_url': 'https://dergipark.org.tr/en/download/article-file/5155821', 'source': {'id': 'https://openalex.org/S4210190824', 'display_name': 'Participatory Educational Research', 'issn_l': '2148-6123', 'issn': ['2148-6123'], 'is_oa': True, 'is_in_doaj': False, 'is_core': False, 'host_organization': None, 'host_organization_name': None, 'host_organization_lineage': [], 'host_organization_lineage_names': [], 'type': 'journal'}, 'license': 'cc-by', 'license_id': 'https://openalex.org/licenses/cc-by', 'version': 'publishedVersion', 'is_accepted': True, 'is_published': True, 'raw_source_name': 'Participatory Educational Research', 'raw_type': 'journal-article'}",article,...,[],"{'This': [0], 'study': [1], 'aims': [2], 'to': [3, 112, 157, 196, 213], 'investigate': [4], 'the': [5, 55, 70], 'social': [6], 'and': [7, 14, 23, 49, 69, 99, 116, 172, 185, 188, 192, 209, 220, 237], 'cultural': [8, 186, 250], 'informal': [9], 'learning': [10], 'opportunities': [11], 'of': [12, 25, 30, 73, 160, 215], 'middle': [13], 'high': [15], 'school': [16], 'students': [17, 32, 101, 110, 121, 153, 165, 170, 190, 239, 244], 'based': [18], 'on': [19, 93, 149], 'gender,': [20], 'grade': [21], 'level,': [22], 'place': [24, 214], 'residence.': [26, 216], 'The': [27, 61, 75], 'sample': [28], 'consists': [29], '1,310': [31], 'from': [33, 218, 230], 'a': [34, 90, 146, 158, 246], 'province': [35], 'located': [36], 'in': [37, 54, 105, 128, 198, 206, 224], 'eastern': [38], 'Türkiye.': [39], 'Data': [40], 'were': [41, 63, 154, 180, 204], 'collected': [42], 'through': [43], 'three': [44], 'items': [45, 53], 'concerning': [46], 'personal': [47], 'information': [48], 'two': [50], 'special': [51], 'multiple-response': [52], 'Informal': [56], 'Learning': [57], 'Opportunities': [58], 'Test': [59], '(ILOT).': [60], 'data': [62], 'analyzed': [64], 'using': [65], 'multiple': [66], 'response': [67], 'analysis': [68], 'chi-square': [71], 'test': [72], 'independence.': [74], 'results': [76], 'indicated': [77], 'that': [78], 'gender': [79], 'did': [80, 138], 'not': [81, 139], 'significantly': [82, 140], 'influence': [83, 148], 'students’': [84], 'camp': [85, 142, 161, 208], 'preferences;': [86], 'however,': [87], 'it': [88], 'had': [89], 'significant': [91, 147, 202], 'effect': [92], 'their': [94], 'activity': [95, 150, 210], 'preferences.': [96, 151], 'Both': [97], 'boy': [98, 120], 'girl': [100, 109], 'exhibited': [102], 'low': [103, 132], 'participation': [104], 'science': [106, 184], 'camps,': [107], 'yet': [108], 'tended': [111, 195], 'prefer': [113], 'social,': [114], 'cultural,': [115], 'nature-based': [117, 241], 'activities,': [118, 242], 'while': [119], 'favored': [122], 'physical': [123], 'or': [124, 232], 'technical': [125], ...}",[],2026-03-10T16:38:18.471706,2026-03-09T00:00:00,"This study aims to investigate the social and cultural informal learning opportunities of middle and high school students based on gender, grade level, and place of residence. The sample consists of 1,310 students from a province located in eastern Türkiye. Data were collected through three items concerning personal information and two special multiple-response items in the Informal Learning Opportunities Test (ILOT). The data were analyzed using multiple response analysis and the chi-square test of independence. The results indicated that gender did not significantly influence students’ camp preferences; however, it had a significant effect on their activity preferences. Both boy and girl students exhibited low participation in science camps, yet girl students tended to prefer social, cultural, and nature-based activities, while boy students favored physical or technical activities. Participation in STEM-related activities was low for both genders. Grade level did not significantly affect camp preferences but showed a significant influence on activity preferences. Upper-grade students were more open to a variety of camp experiences, whereas 10th-grade students demonstrated limited participation. Younger students (5th and 6th graders) preferred entertainment-oriented visits, 7th graders were more inclined toward science and cultural trips, and older students (9th and 10th graders) tended to engage in vocational visits. Moreover, significant differences were found in both camp and activity preferences according to place of residence. Students from city and district areas participated in camps more frequently than those from villages or metropolitan regions. While village and district students preferred nature-based activities, city students showed a greater inclination toward cultural activities.","This study aims to investigate the social and cultural informal learning opportunities of middle and high school students based on gender, grade level, and place of residence. The sample consists of 1,310 students from a province located in eastern Türkiye. Data were collected through three items concerning personal information and two special multiple-response items in the Informal Learning Opportunities Test (ILOT). The data were analyzed using multiple response analysis and the chi-square test of independence. The results indicated that gender did not significantly influence students’ camp preferences; however, it had a significant effect on their activity preferences. Both boy and girl students exhibited low participation in science camps, yet girl students tended to prefer social, cultural, and nature-based activities, while boy students favored physical or technical activities. Participation in STEM-related activities was low for both genders. Grade level did not significantly affect camp preferences but showed a significant influence on activity preferences. Upper-grade students were more open to a variety of camp experiences, whereas 10th-grade students demonstrated limited participation. Younger students (5th and 6th graders) preferred entertainment-oriented visits, 7th graders were more inclined toward science and cultural trips, and older students (9th and 10th graders) tended to engage in vocational visits. Moreover, significant differences were found in both camp and activity preferences according to place of residence. Students from city and district areas participated in camps more frequently than those from villages or metropolitan regions. While village and district students preferred nature-based activities, city students showed a greater inclination toward cultural activities.",252.0,"[students, were, preferences, activities, cultural, grade, camp, significant, activity, both]","{'this': 1, 'study': 1, 'aims': 1, 'investigate': 1, 'the': 3, 'social': 1, 'and': 14, 'cultural': 1, 'informal': 1, 'learning': 1, 'opportunities': 1, 'middle': 1, 'high': 1, 'school': 1, 'students': 1, 'based': 1, 'gender': 1, 'grade': 1, 'level': 1, 'place': 2, 'residence': 2, 'sample': 1, 'consists': 1, '1310': 1, 'from': 3, 'province': 1, 'located': 1, 'eastern': 1, 'türkiye': 1, 'data': 1, 'were': 5, 'collected': 1, 'through': 1, 'three': 1, 'items': 2, 'concerning': 1, 'personal': 1, 'information': 1, 'two': 1, 'special': 1, 'multipleresponse': 1, 'test': 1, 'ilot': 1, 'analyzed': 1, 'using': 1, 'multiple': 1, 'response': 1, 'analysis': 1, 'chisquare': 1, 'independence': 1, 'results': 1, 'indicated': 1, 'that': 1, 'did': 2, 'not': 2, 'significantly': 2, 'influence': 2, 'camp': 4, 'preferences': 2, 'however': 1, 'had': 1, 'significant': 3, 'effect': 1, 'their': 1, 'activity': 3, 'both': 2, 'boy': 2, 'girl': 2, 'exhibited': 1, 'low': 2, 'participation': 1, 'science': 2, 'camps': 1, 'yet': 1, 'tended': 2, 'prefer': 1, 'naturebased': 2, 'activities': 1, 'while': 1, 'favored': 1, 'physical': 1, 'technical': 1, 'stemrelated': 1, 'was': 1, 'for': 1, 'genders': 1, 'affect': 1, 'but': 1, 'showed': 2, 'uppergrade': 1, 'more': 3, 'open': 1, 'variety': 1, 'experiences': 1, 'whereas': 1, '10thgrade': 1, 'demonstrated': 1, 'limited': 1, 'younger': 1, '5th': 1, ...}"
1,https://openalex.org/W7125368247,https://doi.org/10.1007/s10857-025-09739-6,How can teachers learn to teach effectively and equitably?,How can teachers learn to teach effectively and equitably?,2026,2026-01-22,"{'openalex': 'https://openalex.org/W7125368247', 'doi': 'https://doi.org/10.1007/s10857-025-09739-6'}",en,"{'id': 'doi:10.1007/s10857-025-09739-6', 'is_oa': False, 'landing_page_url': 'https://doi.org/10.1007/s10857-025-09739-6', 'pdf_url': None, 'source': {'id': 'https://openalex.org/S64545302', 'display_name': 'Journal of Mathematics Teacher Education', 'issn_l': '1386-4416', 'issn': ['1386-4416', '1573-1820'], 'is_oa': False, 'is_in_doaj': False, 'is_core': True, 'host_organization': 'https://openalex.org/P4310319900', 'host_organization_name': 'Springer Science+Business Media', 'host_organization_lineage': ['https://openalex.org/P4310319900', 'https://openalex.org/P4310319965'], 'host_organization_lineage_names': ['Springer Science+Business Media', 'Springer Nature'], 'type': 'journal'}, 'license': None, 'license_id': None, 'version': 'publishedVersion', 'is_accepted': True, 'is_published': True, 'raw_source_name': 'Journal of Mathematics Teacher Education', 'raw_type': 'journal-article'}",article,...,[],None,[],2026-01-26T23:06:41.788003,2026-01-23T00:00:00,NaN,NaN,NaN,None,None
2,https://openalex.org/W7125377449,https://doi.org/10.1002/bse.70489,Rethinking ESG‐Financial Performance Nexus Beyond Linearity: A Configurational Analysis,Rethinking ESG‐Financial Performance Nexus Beyond Linearity: A Configurational Analysis,2026,2026-01-21,"{'openalex': 'https://openalex.org/W7125377449', 'doi': 'https://doi.org/10.1002/bse.70489'}",en,"{'id': 'doi:10.1002/bse.70489', 'is_oa': False, 'landing_page_url': 'https://doi.org/10.1002/bse.70489', 'pdf_url': None, 'source': {'id': 'https://openalex.org/S205793605', 'display_name': 'Business Strategy and the Environment', 'issn_l': '0964-4733', 'issn': ['0964-4733', '1099-0836'], 'is_oa': False, 'is_in_doaj': False, 'is_core': True, 'host_organization': 'https://openalex.org/P4310320595', 'host_organization_name': 'Wiley', 'host_organization_lineage': ['https://openalex.org/P4310320595'], 'host_organization_lineage_names': ['Wiley'], 'type': 'journal'}, 'license': None, 'license_id': None, 'version': 'publishedVersion', 'is_accepted': True, 'is_published': True, 'raw_source_name': 'Business Strategy and the Environment', 'raw_type': 'journal-article'}",article,...,[],"{'ABSTRACT': [0], 'Pressures': [1], 'to': [2, 71, 133], 'reconcile': [3], 'both': [4], 'sustainability': [5], 'commitments': [6], 'and': [7, 22, 26, 33, 40, 50, 75, 80, 109, 114, 126], 'financial': [8, 17, 27], 'targets': [9], 'exert': [10], 'inherent': [11], 'trade‐offs': [12], 'for': [13, 122, 130], 'firms,': [14], 'especially': [15], 'under': [16], 'constraints.': [18], 'The': [19], 'environmental,': [20], 'social,': [21], 'governance': [23], 'performance': [24, 28], '(ESGP)': [25], '(FP)': [29], 'link': [30], 'is': [31], 'multifaceted': [32], 'cannot': [34], 'be': [35], 'sufficiently': [36], 'captured': [37], 'by': [38], 'unidirectional': [39], 'linear': [41], 'models.': [42], 'To': [43], 'explore': [44], 'how': [45], 'the': [46, 61], 'overall': [47], 'ESG': [48, 52, 107], 'scores': [49], 'individual': [51], 'scores,': [53], 'alongside': [54], 'firm': [55, 110], 'size,': [56], 'impact': [57], 'FP,': [58], 'we': [59], 'employ': [60], 'Fuzzy‐Set': [62], 'Qualitative': [63], 'Comparative': [64], 'Analysis': [65], '(fsQCA),': [66], 'a': [67, 84, 119], 'structured': [68], 'methodology': [69], 'designed': [70], 'uncover': [72], 'conjunctural': [73], 'pathways': [74], 'causal': [76], 'relationships': [77], 'between': [78], 'ESGP': [79], 'FP.': [81], 'Based': [82], 'on': [83], 'sample': [85], 'consisting': [86], 'of': [87], 'nonfinancial': [88], 'firms': [89], 'listed': [90], 'in': [91], 'Borsa': [92], 'Istanbul': [93], 'over': [94], '2019–2021,': [95], 'our': [96], 'outcomes': [97], 'reveal': [98], 'four': [99], 'distinct': [100], 'configurations': [101], 'that': [102, 105], 'commonly': [103], 'demonstrate': [104], 'each': [106], 'pillar': [108], 'size': [111], 'have': [112], 'conditional': [113], 'asymmetric': [115], 'effects.': [116], 'We': [117], 'contribute': [118], ...}",[],2026-03-06T13:50:29.536080,2026-01-23T00:00:00,"ABSTRACT Pressures to reconcile both sustainability commitments and financial targets exert inherent trade‐offs for firms, especially under financial constraints. The environmental, social, and governance performance (ESGP) and financial performance (FP) link is multifaceted and cannot be sufficiently captured by unidirectional and linear models. To explore how the overall ESG scores and individual ESG scores, alongside firm size, impact FP, we employ the Fuzzy‐Set Qualitative Comparative Analysis (fsQCA), a structured methodology designed to uncover conjunctural pathways and causal relationships between ESGP and FP. Based on a sample consisting of nonfinancial firms listed in Borsa Istanbul over 2019–2021, our outcomes reveal four distinct configurations that commonly demonstrate that each ESG pillar and firm size have conditional and asymmetric effects. We contribute a holistic approach for understanding ESGP–FP dynamics and offer strategic insights for several stakeholders to allocate resources more effectively.","Pressures to reconcile both sustainability commitments and financial targets exert inherent trade‐offs for firms, especially under financial constraints. The environmental, social, and governance performance (ESGP) and financial performance (FP) link is multifaceted and cannot be sufficiently captured by unidirectional and linear models. To explore how the overall ESG scores and individual ESG scores, alongside firm size, impact FP, we employ the Fuzzy‐Set Qualitative Comparative Analysis (fsQCA), a structured methodology designed to uncover conjunctural pathways and causal relationships between ESGP and FP. Based on a sample consisting of nonfinancial firms listed in Borsa Istanbul over 2019–2021, our outcomes reveal four distinct configurations that commonly demonstrate that each ESG pillar and firm size have conditional and asymmetric effects. We contribute a holistic approach for understanding ESGP–FP dynamics and offer strategic insights for several stakeholders to allocate resources more effectively.",137.0,"[financial, esgp, firms, performance, scores, firm, size, pressures, reconcile, both]","{'abstract': 1, 'pressures': 1, 'reconcile': 1, 'both': 1, 'sustainability': 1, 'commitments': 1, 'and': 11, 'financial': 3, 'targets': 1, 'exert': 1, 'inherent': 1, 'tradeoffs': 1, 'for': 3, 'firms': 1, 'especially': 1, 'under': 1, 'constraints': 1, 'the': 2, 'environmental': 1, 'social': 1, 'governance': 1, 'performance': 2, 'esgp': 1, 'link': 1, 'multifaceted': 1, 'cannot': 1, 'sufficiently': 1, 'captured': 1, 'unidirectional': 1, 'linear': 1, 'models': 1, 'explore': 1, 'how': 1, 'overall': 1, 'esg': 3, 'scores': 1, 'individual': 1, 'alongside': 1, 'firm': 2, 'size': 1, 'impact': 1, 'employ': 1, 'fuzzyset': 1, 'qualitative': 1, 'comparative': 1, 'analysis': 1, 'fsqca': 1, 'structured': 1, 'methodology': 1, 'designed': 1, 'uncover': 1, 'conjunctural': 1, 'pathways': 1, 'causal': 1, 'relationships': 1, 'between': 1, 'based': 1, 'sample': 1, 'consisting': 1, 'nonfinancial': 1, 'listed': 1, 'borsa': 1, 'istanbul': 1, 'over': 1, '20192021': 1, 'our': 1, 'outcomes': 1, 'reveal': 1, 'four': 1, 'distinct': 1, 'configurations': 1, 'that': 2, 'commonly': 1, 'demonstrate': 1, 'each': 1, 'pillar': 1, 'have': 1, 'conditional': 1, 'asymmetric': 1, 'effects': 1, 'contribute': 1, 'holistic': 1, 'approach': 1, 'understanding': 1, 'esgpfp': 1, 'dynamics': 1, 'offer': 1, 'strategic': 1, 'insights': 1, 'several': 1, 'stakeholders': 1, 'allocate': 1, 'resources': 1, 'more': 1, 'effectively': 1}"
3,https://openalex.org/W7125416384,https://doi.org/10.1080/00368121.2026.2615961,Computational thinking meets robotics: using mBot2 to explore kinematics concepts in physics classrooms,Computational thinking meets robotics: using mBot2 to explore kinematics concepts in physics classrooms,2026,2026-01-21,"{'openalex': 'https://openalex.org/W7125416384', 'doi': 'https://doi.org/10.1080/00368121.2026.2615961'}",en,"{'id': 'doi:10.1080/00368121.2026.2615961', 'is_oa': False, 'landing_page_url': 'https://doi.org/10.1080/00368121.2026.2615961', 'pdf_url': None, 'source': {'id': 'https://openalex.org/S95132780', 'display_name': 'Science Activities', 'issn_l': '0036-8121', 'issn': ['0036-8121', '1940-1302'], 'is_oa': False, 'is_in_doaj': False, 'is_core': True, 'host_organization': 'https://openalex.org/P4310320547', 'host_organization_name': 'Taylor & Francis', 'host_organization_lineage': ['https://openalex.org/P4310320547'], 'host_organization_lineage_names': ['Taylor & Francis'], 'type': 'journal'}, 'license': None, 'license_id': None, 'version': 'publishedVersion', 'is_accepted': True, 'is_published': True, 'raw_source_name': 'Science Activities', 'raw_type': 'journal-article'}",article,...,[],None,[],2026-01-23T23:24:52.574035,2026-01-23T00:00:00,NaN,NaN,NaN,None,None

In [21]:
priority_followed.head()

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,...,related_works,abstract_inverted_index,counts_by_year,updated_date,created_date,abstract_raw,abstract,abstract_word_count,abstract_keywords,word_frequency
0,https://openalex.org/W1498342204,https://doi.org/10.1145/3788687,An Introduction to Input/Output Automata,An Introduction to Input/Output Automata,2026,2026-01-27,"{'openalex': 'https://openalex.org/W1498342204', 'doi': 'https://doi.org/10.1145/3788687', 'mag': '1498342204'}",en,"{'id': 'doi:10.1145/3788687', 'is_oa': True, 'landing_page_url': 'https://doi.org/10.1145/3788687', 'pdf_url': None, 'source': {'id': 'https://openalex.org/S128250343', 'display_name': 'Formal Aspects of Computing', 'issn_l': '0934-5043', 'issn': ['0934-5043', '1433-299X'], 'is_oa': False, 'is_in_doaj': False, 'is_core': True, 'host_organization': 'https://openalex.org/P4310319900', 'host_organization_name': 'Springer Science+Business Media', 'host_organization_lineage': ['https://openalex.org/P4310319900', 'https://openalex.org/P4310319965'], 'host_organization_lineage_names': ['Springer Science+Business Media', 'Springer Nature'], 'type': 'journal'}, 'license': 'cc-by', 'license_id': 'https://openalex.org/licenses/cc-by', 'version': 'publishedVersion', 'is_accepted': True, 'is_published': True, 'raw_source_name': 'Formal Aspects of Computing', 'raw_type': 'journal-article'}",article,...,"[https://openalex.org/W3144368627, https://openalex.org/W3137220996, https://openalex.org/W2611515161, https://openalex.org/W2328819335, https://openalex.org/W2293287097, https://openalex.org/W2137865376, https://openalex.org/W2117189826, https://openalex.org/W2112640524, https://openalex.org/W2101939036, https://openalex.org/W2101508170, https://openalex.org/W2099529102, https://openalex.org/W2085407655, https://openalex.org/W2043801088, https://openalex.org/W2035362408, https://openalex.org/W2023808162, https://openalex.org/W2015688007, https://openalex.org/W2000302396, https://openalex.org/W1857327297, https://openalex.org/W1506588809, https://openalex.org/W1503973138]","{'We': [0, 15], 'describe': [1], 'the': [2, 17, 20, 35, 39], 'input/output': [3], 'automaton': [4], 'model,': [5, 18], 'a': [6, 29], 'model': [7, 21, 40], 'for': [8], 'concurrent': [9], 'and': [10, 28, 33], 'distributed': [11], 'discrete': [12], 'event': [13], 'systems.': [14], 'define': [16], 'illustrate': [19], 'with': [22], 'several': [23], 'examples': [24], 'concerning': [25], 'vending': [26], 'machines': [27], 'leader': [30], 'election': [31], 'algorithm,': [32], 'survey': [34], 'ways': [36], 'in': [37], 'which': [38], 'has': [41], 'been': [42], 'used.': [43]}","[{'year': 2024, 'cited_by_count': 2}, {'year': 2023, 'cited_by_count': 8}, {'year': 2022, 'cited_by_count': 6}, {'year': 2021, 'cited_by_count': 17}, {'year': 2020, 'cited_by_count': 19}, {'year': 2019, 'cited_by_count': 22}, {'year': 2018, 'cited_by_count': 19}, {'year': 2017, 'cited_by_count': 24}, {'year': 2016, 'cited_by_count': 23}, {'year': 2015, 'cited_by_count': 23}, {'year': 2014, 'cited_by_count': 35}, {'year': 2013, 'cited_by_count': 43}, {'year': 2012, 'cited_by_count': 48}]",2026-03-08T08:50:53.379069,2016-06-24T00:00:00,"We describe the input/output automaton model, a model for concurrent and distributed discrete event systems. We define the model, illustrate the model with several examples concerning vending machines and a leader election algorithm, and survey the ways in which the model has been used.","We describe the input/output automaton model, a model for concurrent and distributed discrete event systems. We define the model, illustrate the model with several examples concerning vending machines and a leader election algorithm, and survey the ways in which the model has been used.",44.0,"[model, describe, input, output, automaton, concurrent, distributed, discrete, event, systems]","{'describe': 1, 'the': 5, 'inputoutput': 1, 'automaton': 1, 'model': 3, 'for': 1, 'concurrent': 1, 'and': 3, 'distributed': 1, 'discrete': 1, 'event': 1, 'systems': 1, 'define': 1, 'illustrate': 1, 'with': 1, 'several': 1, 'examples': 1, 'concerning': 1, 'vending': 1, 'machines': 1, 'leader': 1, 'election': 1, 'algorithm': 1, 'survey': 1, 'ways': 1, 'which': 1, 'has': 1, 'been': 1, 'used': 1}"
1,https://openalex.org/W4406633044,https://doi.org/10.1038/s41562-024-02090-5,Trust in scientists and their role in society across 68 countries,Trust in scientists and their role in society across 68 countries,2025,2025-01-20,"{'openalex': 'https://openalex.org/W4406633044', 'doi': 'https://doi.org/10.1038/s41562-024-02090-5', 'pmid': 'https://pubmed.ncbi.nlm.nih.gov/39833424'}",en,"{'id': 'doi:10.1038/s41562-024-02090-5', 'is_oa': True, 'landing_page_url': 'https://doi.org/10.1038/s41562-024-02090-5', 'pdf_url': 'https://www.nature.com/articles/s41562-024-02090-5.pdf', 'source': {'id': 'https://openalex.org/S2764866340', 'display_name': 'Nature Human Behaviour', 'issn_l': '2397-3374', 'issn': ['2397-3374'], 'is_oa': False, 'is_in_doaj': False, 'is_core': True, 'host_organization': 'https://openalex.org/P4310319908', 'host_organization_name': 'Nature Portfolio', 'host_organization_lineage': ['https://openalex.org/P4310319908', 'https://openalex.org/P4310319965'], 'host_organization_lineage_names': ['Nature Portfolio', 'Springer Nature'], 'type': 'journal'}, 'license': 'cc-by', 'license_id': 'https://openalex.org/licenses/cc-by', 'version': 'publishedVersion', 'is_accepted': True, 'is_published': True, 'raw_source_name': 'Nature Human Behaviour', 'raw_type': 'journal-article'}",article,...,"[https://openalex.org/W2560936962, https://openalex.org/W2788727012, https://openalex.org/W4388203630, https://openalex.org/W2526386912, https://openalex.org/W2410591377, https://openalex.org/W2323113755, https://openalex.org/W2104953402, https://openalex.org/W2506793457, https://openalex.org/W2604195860, https://openalex.org/W4327503229]","{'Science': [0], 'is': [1, 99], 'crucial': [2], 'for': [3, 135], 'evidence-based': [4], 'decision-making.': [5], 'Public': [6], 'trust': [7, 43, 66, 104, 115, 144], 'in': [8, 27, 44, 61, 75, 105, 116, 129, 145], 'scientists': [9, 67, 71, 117, 136], 'can': [10], 'help': [11], 'decision': [12], 'makers': [13], 'act': [14], 'on': [15], 'the': [16, 19, 30, 110], 'basis': [17], 'of': [18, 33, 55, 103, 114, 126], 'best': [20], 'available': [21], 'evidence,': [22], 'especially': [23], 'during': [24], 'crises.': [25], 'However,': [26], 'recent': [28], 'years': [29], 'epistemic': [31], 'authority': [32], 'science': [34], 'has': [35], 'been': [36], 'challenged,': [37], 'causing': [38], 'concerns': [39, 49], 'about': [40], 'low': [41], 'public': [42], 'scientists.': [45, 146], 'We': [46, 79], 'interrogated': [47], 'these': [48], 'with': [50, 89], 'a': [51, 120], 'preregistered': [52], '68-country': [53], 'survey': [54], '71,922': [56], 'respondents': [57], 'and': [58, 68, 77, 83, 91, 137, 142], 'found': [59, 80], 'that': [60, 70, 112], 'most': [62, 64], 'countries,': [63, 85], 'people': [65], 'agree': [69], 'should': [72], 'engage': [73], 'more': [74], 'society': [76], 'policymaking.': [78, 130], 'variations': [81], 'between': [82], 'within': [84], 'which': [86], 'we': [87, 107], 'explain': [88], 'individual-': [90], 'country-level': [92], 'variables,': [93], 'including': [94], 'political': [95], 'orientation.': [96], 'While': [97], 'there': [98], 'no': [100], 'widespread': [101], 'lack': [102, 113], 'scientists,': [106], 'cannot': [108], 'discount': [109], 'concern': [111], 'by': [118], 'even': [119], 'small': [121], 'minority': [122], 'may': [123], 'affect': [124], 'considerations': [125], 'scientific': [127], 'evidence': [128], 'These': [131], 'findings': [132], 'have': [133], 'implications': [134], 'policymakers': [138], 'seeking': [139], 'to': [140], 'maintain': [141], ...}","[{'year': 2026, 'cited_by_count': 31}, {'year': 2025, 'cited_by_count': 137}, {'year': 2024, 'cited_by_count': 2}]",2026-03-10T16:38:18.471706,2025-10-10T00:00:00,"Science is crucial for evidence-based decision-making. Public trust in scientists can help decision makers act on the basis of the best available evidence, especially during crises. However, in recent years the epistemic authority of science has been challenged, causing concerns about low public trust in scientists. We interrogated these concerns with a preregistered 68-country survey of 71,922 respondents and found that in most countries, most people trust scientists and agree that scientists should engage more in society and policymaking. We found variations between and within countries, which we explain with individual- and country-level variables, including political orientation. While there is no widespread lack of trust in scientists, we cannot discount the concern that lack of trust in scientists by even a small minority may affect considerations of scientific evidence in policymaking. These findings have implications for scientists and policymakers seeking to maintain and increase trust in scientists.","Science is crucial for evidence-based decision-making. Public trust in scientists can help decision makers act on the basis of the best available evidence, especially during crises. However, in recent years the epistemic authority of science has been challenged, causing concerns about low public trust in scientists. We interrogated these concerns with a preregistered 68-country survey of 71,922 respondents and found that in most countries, most people trust scientists and agree that scientists should engage more in society and policymaking. We found variations between and within countries, which we explain with individual- and country-level variables, including political orientation. While there is no widespread lack of trust in scientists, we cannot discount the concern that lack of trust in scientists by even a small minority may affect considerations of scientific evidence in policymaking. These findings have implications for scientists and policymakers seeking to maintain and increase trust in scientists.",147.0,"[scientists, trust, evidence, science, decision, public, concerns, country, found, most]","{'science': 1, 'crucial': 1, 'for': 2, 'evidencebased': 1, 'decisionmaking': 1, 'public': 1, 'trust': 6, 'scientists': 1, 'can': 1, 'help': 1, 'decision': 1, 'makers': 1, 'act': 1, 'the': 4, 'basis': 1, 'best': 1, 'available': 1, 'evidence': 1, 'especially': 1, 'during': 1, 'crises': 1, 'however': 1, 'recent': 1, 'years': 1, 'epistemic': 1, 'authority': 1, 'has': 1, 'been': 1, 'challenged': 1, 'causing': 1, 'concerns': 2, 'about': 1, 'low': 1, 'interrogated': 1, 'these': 1, 'with': 2, 'preregistered': 1, '68country': 1, 'survey': 1, '71922': 1, 'respondents': 1, 'and': 7, 'found': 2, 'that': 3, 'most': 2, 'countries': 2, 'people': 1, 'agree': 1, 'should': 1, 'engage': 1, 'more': 1, 'society': 1, 'policymaking': 2, 'variations': 1, 'between': 1, 'within': 1, 'which': 1, 'explain': 1, 'individual': 1, 'countrylevel': 1, 'variables': 1, 'including': 1, 'political': 1, 'orientation': 1, 'while': 1, 'there': 1, 'widespread': 1, 'lack': 2, 'cannot': 1, 'discount': 1, 'concern': 1, 'even': 1, 'small': 1, 'minority': 1, 'may': 1, 'affect': 1, 'considerations': 1, 'scientific': 1, 'findings': 1, 'have': 1, 'implications': 1, 'policymakers': 1, 'seeking': 1, 'maintain': 1, 'increase': 1}"

In [22]:
import pandas as pd
import json
import os

def create_benchmark_pairs(priority_df, boun_df, output_path='eval_dataset/benchmark_pairs.json'):
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    benchmark_data = []
    
    priority_df = priority_df.dropna(subset=['abstract']).copy()
    boun_df = boun_df.dropna(subset=['abstract']).copy()

    test_queries = priority_df.head(50)
    
    for _, query_row in test_queries.iterrows():
        # OpenAlex 'related_works'
        related_ids = query_row.get('related_works', [])
        if not isinstance(related_ids, list): related_ids = []
        
        # 1. Direct Match
        positives = boun_df[boun_df['id'].isin(related_ids)].copy()
        
        # 2. Concept Match
        if positives.empty:
            q_concepts = [c['id'] for c in query_row['concepts']] if isinstance(query_row['concepts'], list) else []
            if q_concepts:
                positives = boun_df[boun_df['concepts'].apply(
                    lambda x: any(c['id'] in q_concepts for c in x) if isinstance(x, list) else False
                )].head(3)

        if not positives.empty:
            benchmark_data.append({
                "query": {
                    "id": query_row['id'],
                    "title": query_row['title'],
                    "abstract": query_row['abstract']
                },
                "positives": positives[['id', 'title']].to_dict('records')
            })

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(benchmark_data, f, ensure_ascii=False, indent=4)
    
    return len(benchmark_data)

In [23]:
pairs_count = create_benchmark_pairs(priority_followed, boun)
pairs_count

50

In [24]:
import json
import pandas as pd

with open('eval_dataset/benchmark_pairs.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

flat_list = []
for entry in data:
    query_title = entry['query']['title']
    query_abstract = entry['query']['abstract']
    if entry['positives']:
        match = entry['positives'][0]
        flat_list.append({
            "Global_Query_Text": query_title + " " + query_abstract, 
            "BOUN_Match_Text": match['title'],
            "Match_Count": len(entry['positives']) 
        })

df_view = pd.DataFrame(flat_list)

pd.set_option('display.max_colwidth', None)
df_view = df_view.sort_values(by='Match_Count', ascending=False)
df_view

,Global_Query_Text,BOUN_Match_Text,Match_Count
0,"An Introduction to Input/Output Automata We describe the input/output automaton model, a model for concurrent and distributed discrete event systems. We define the model, illustrate the model with several examples concerning vending machines and a leader election algorithm, and survey the ways in which the model has been used.",Machine learning for risk profiling: An analysis of pension fund participants,3
37,"Development and future of droplet microfluidics Over the past two decades, advances in droplet-based microfluidics have facilitated new approaches to process and analyze samples with unprecedented levels of precision and throughput. A wide variety of applications has been inspired across multiple disciplines ranging from materials science to biology. Understanding the dynamics of droplets enables optimization of microfluidic operations and design of new techniques tailored to emerging demands. In this review, we discuss the underlying physics behind high-throughput generation and manipulation of droplets. We also summarize the applications in droplet-derived materials and droplet-based lab-on-a-chip biotechnology. In addition, we offer perspectives on future directions to realize wider use of droplet microfluidics in industrial production and biomedical analyses.",Machine learning for risk profiling: An analysis of pension fund participants,3
27,"Adverse Childhood Experiences and Adult Mental Health Outcomes This study found that associations between ACEs and adult mental health outcomes remained after controlling for shared genetic and environmental factors, which was particularly evident after multiple ACEs or sexual abuse. These findings suggest that targeted interventions may be associated with reduced risks of future psychopathology.",Investigation of Social and Cultural Informal Learning Opportunities for Middle and High School Students,3
28,"Priming agents transiently reduce the clearance of cell-free DNA to improve liquid biopsies Liquid biopsies enable early detection and monitoring of diseases such as cancer, but their sensitivity remains limited by the scarcity of analytes such as cell-free DNA (cfDNA) in blood. Improvements to sensitivity have primarily relied on enhancing sequencing technology ex vivo. We sought to transiently augment the level of circulating tumor DNA (ctDNA) in a blood draw by attenuating its clearance in vivo. We report two intravenous priming agents given 1 to 2 hours before a blood draw to recover more ctDNA. Our priming agents consist of nanoparticles that act on the cells responsible for cfDNA clearance and DNA-binding antibodies that protect cfDNA. In tumor-bearing mice, they greatly increase the recovery of ctDNA and improve the sensitivity for detecting small tumors.",Evaluating Batch Correction Methods for Large-Scale Mass Spectrometry Imaging of Heterogeneous Tissues,3
29,"Large Legal Fictions: Profiling Legal Hallucinations in Large Language Models Do large language models (LLMs) know the law? LLMs are increasingly being used to augment legal practice, education, and research, yet their revolutionary potential is threatened by the presence of “hallucinations”—textual output that is not consistent with legal facts. We present the first systematic evidence of these hallucinations in public-facing LLMs, documenting trends across jurisdictions, courts, time periods, and cases. Using OpenAI’s ChatGPT 4 and other public models, we show that LLMs hallucinate at least 58% of the time, struggle to predict their own hallucinations, and often uncritically accept users’ incorrect legal assumptions. We conclude by cautioning against the rapid and unsupervised integration of popular LLMs into legal tasks, and we develop a typology of legal hallucinations to guide future research in this area.",Investigation of Social and Cultural Informal Learning Opportunities for Middle and High School Students,3
30,"Foundation models in robotics: Applications, challenges, and the future We survey applications of pretrained foundation models in robotics. Traditional deep learning models in robotics are trained on small datasets tailored for specific tasks, which limits their adaptability across diverse applications. In contrast, foundation models pretrained on internet-scale data appear to have superior generalization capabilities, and in some instances display an emergent ability to find zero-shot solutions to problems that are not present in the training data. Foundation models may hold the potential to enhance various components of the robot autonomy stack, from perception to decision-making and control. For example, large language models can generate code or provide common sense reasoning, while vision-language models enable open-vocabulary visual recognition. However, significant open research challenges remain, particularly around the scarcity of robot-relevant training data, safety guarantees and uncertainty quantification, and real-time execution. In this survey, we study recent papers that have used or built foundation models to solve robotics problems. We explore how foundation models contribute to improving robot capabilities in the domains of perception, decision-making, and control. We discuss the challenges hindering the adoption of foundation models in robot autonomy and provide opportunities and potential pathways for future advancements. The GitHub project corresponding to this paper can be found here: .",Machine learning for risk profiling: An analysis of pension fund participants,3
31,"The Galaxy platform for accessible, reproducible, and collaborative data analyses: 2024 update Galaxy ( is deployed globally, predominantly through free-to-use services, supporting user-driven research that broadens in scope each year. Users are attracted to public Galaxy services by platform stability, tool and reference dataset diversity, training, support and integration, which enables complex, reproducible, shareable data analysis. Applying the principles of user experience design (UXD), has driven improvements in accessibility, tool discoverability through Galaxy Labs/subdomains, and a redesigned Galaxy ToolShed. Galaxy tool capabilities are progressing in two strategic directions: integrating general purpose graphical processing units (GPGPU) access for cutting-edge methods, and licensed tool support. Engagement with global research consortia is being increased by developing more workflows in Galaxy and by resourcing the public Galaxy services to run them. The Galaxy Training Network (GTN) portfolio has grown in both size, and accessibility, through learning paths and direct integration with Galaxy tools that feature in training courses. Code development continues in line with the Galaxy Project roadmap, with improvements to job scheduling and the user interface. Environmental impact assessment is also helping engage users and developers, reminding them of their role in sustainability, by displaying estimated CO2 emissions generated by each Galaxy job.",Massive runaway star HD 254577: The pre-supernova binary companion to the progenitor of the supernova remnant IC 443,3
32,"Ribociclib plus Endocrine Therapy in Early Breast Cancer Ribociclib plus an NSAI significantly improved invasive disease-free survival among patients with HR-positive, HER2-negative stage II or III early breast cancer. (Funded by Novartis; NATALEE ClinicalTrials.gov number, NCT03701334.).",Smart sanitary hardware for health monitoring,3
33,"UNETR++: Delving Into Efficient and Accurate 3D Medical Image Segmentation Owing to the success of transformer models, recent works study their applicability in 3D medical segmentation tasks. Within the transformer models, the self-attention mechanism is one of the main building blocks that strives to capture long-range dependencies, compared to the local convolutional-based design. However, the self-attention operation has quadratic complexity which proves to be a computational bottleneck, especially in volumetric medical imaging, where the inputs are 3D with numerous slices. In this paper, we propose a 3D medical image segmentation approach, named UNETR++, that offers both high-quality segmentation masks as well as efficiency in terms of parameters, compute cost, and inference speed. The core of our design is the introduction of a novel efficient paired attention (EPA) block that efficiently learns spatial and channel-wise discriminative features using a pair of inter-dependent branches based on spatial and channel attention. Our spatial attention formulation is efficient and has linear complexity with respect to the input. To enable communication between spatial and channel-focused branches, we share the weights of query and key mapping functions that provide a complimentary benefit (paired attention), while also reducing the complexity. Our extensive evaluations on five benchmarks, Synapse, BTCV, ACDC, BraTS, and Decathlon-Lung, reveal the effectiveness of our contributions in terms of both efficiency and accuracy. On Synapse, our UNETR++ sets a new state-of-the-art with a Dice Score of 87.2%, while significantly reducing parameters and FLOPs by over 71%, compared to the best method in the literature. Our code and models are available at:",Machine learning for risk profiling: An analysis of pension fund participants,3
34,"Translational and Therapeutic Evaluation of RAS-GTP Inhibition by RMC-6236 in RAS-Driven Cancers The discovery of RMC-6236 enables the first-ever therapeutic evaluation of targeted and concurrent inhibition of canonical mutant and wild-type RAS-GTP in RAS-driven cancers. We demonstrate that broad-spectrum RAS-GTP inhibition is tolerable at exposures that induce profound tumor regressions in preclinical models of, and in patients with, such tumors. This article is featured in Selected Articles from This Issue, p. 897.",Smart sanitary hardware for health monitoring,3
35,"InterPro: the protein sequence classification resource in 2025 InterPro ( is a freely accessible resource for the classification of protein sequences into families. It integrates predictive models, known as signatures, from multiple member databases to classify sequences into families and predict the presence of domains and significant sites. The InterPro database provides annotations for over 200 million sequences, ensuring extensive coverage of UniProtKB, the standard repository of protein sequences, and includes mappings to several other major resources, such as Gene Ontology (GO), Protein Data Bank in Europe (PDBe) and the AlphaFold Protein Structure Database. In this publication, we report on the status of InterPro (version 101.0), detailing new developments in the database, associated web interface and software. Notable updates include the increased integration of structures predicted by AlphaFold and the enhanced description of protein families using artificial intelligence. Over the past two years, more than 5000 new InterPro entries have been created. The InterPro website now offers access to 85 000 protein families and domains from its member databases and serves as a long-term archive for retired databases. InterPro data, software and tools are freely available.",Machine learning for risk profiling: An analysis of pension fund participants,3
36,"METhodological RadiomICs Score (METRICS): a quality scoring tool for radiomics research endorsed by EuSoMII • A methodological scoring tool, METRICS, was developed for assessing the quality of radiomics research, with a large international expert panel and a modified Delphi protocol. • The proposed scoring tool presents expert opinion-based importance weights of categories and items with a transparent methodology for the first time. • METRICS accounts for varying use cases, from handcrafted radiomics to entirely deep learning-based pipelines. • A web application has been developed to help with the calculation of the METRICS score ( ) and a repository created to collect feedback from the radiomics community ( ).",Smart sanitary hardware for health monitoring,3
38,"Roadmap for Optical Metasurfaces Metasurfaces have recently risen to prominence in optical research, providing unique functionalities that can be used for imaging, beam forming, holography, polarimetry, and many more, while keeping device dimensions small. Despite the fact that a vast range of basic metasurface designs has already been thoroughly studied in the literature, the number of metasurface-related papers is still growing at a rapid pace, as metasurface research is now spreading to adjacent fields, including computational imaging, augmented and virtual reality, automotive, display, biosensing, nonlinear, quantum and topological optics, optical computing, and more. At the same time, the ability of metasurfaces to perform optical functions in much more compact optical systems has triggered strong and constantly growing interest from various industries that greatly benefit from the availability of miniaturized, highly functional, and efficient optical components that can be integrated in optoelectronic systems at low cost. This creates a truly unique opportunity for the field of metasurfaces to make both a scientific and an industrial impact. The goal of this Roadmap is to mark this ""golden age"" of metasurface research and define future directions to encourage scientists and engineers to drive research and development in the field of metasurfaces toward both scientific excellence and broad industrial adoption.",Massive runaway star HD 254577: The pre-supernova binary companion to the progenitor of the supernova remnant IC 443,3
1,"Trust in scientists and their role in society across 68 countries Science is crucial for evidence-based decision-making. Public trust in scientists can help decision makers act on the basis of the best available evidence, especially during crises. However, in recent years the epistemic authority of science has been challenged, causing concerns about low public trust in scientists. We interrogated these concerns with a preregistered 68-country survey of 71,922 respondents and found that in most countries, most people trust scientists and agree that scientists should engage more in society and policymaking. We found variations between and within countries, which we explain with individual- and country-level variables, including political orientation. While there is no widespread lack of trust in scientists, we cannot discount the concern that lack of trust in scientists by even a small minority may affect considerations of scientific evidence in policymaking. These findings have implications for scientists and policymakers seeking to maintain and increase trust in scientists.",Investigation of Social and Cultural Informal Learning Opportunities for Middle and High School Students,3
39,"Data-driven regularization lowers the size barrier of cryo-EM structure determination Macromolecular structure determination by electron cryo-microscopy (cryo-EM) is limited by the alignment of noisy images of individual particles. Because smaller particles have weaker signals, alignment errors impose size limitations on its applicability. Here, we explore how image alignment is improved by the application of deep learning to exploit prior knowledge about biological macromolecular structures that would otherwise be difficult to express mathematically. We train a denoising convolutional neural network on pairs of half-set reconstructions from the electron microscopy data bank (EMDB) and use this denoiser as an alternative to a commonly used smoothness prior. We demonstrate that this approach, which we call Blush regularization, yields better reconstructions than do existing algorithms, in particular for data with low signal-to-noise ratios. The reconstruction of a protein–nucleic acid complex with a molecular weight of 40 kDa, which was previously intractable, illustrates that denoising neural networks will expand the applicability of cryo-EM structure determination for a wide range of biological macromolecules.",Evaluating Batch Correction Methods for Large-Scale Mass Spectrometry Imaging of Heterogeneous Tissues,3
40,"The Heart of the World Cardiovascular diseases (CVDs) are the leading cause of mortality globally. Of the 20.5 million CVD-related deaths in 2021, approximately 80% occurred in low- and middle-income countries. Using data from the Global Burden of Disease Study, NCD Risk Factor Collaboration, NCD Countdown initiative, WHO Global Health Observatory, and WHO Global Health Expenditure database, we present the burden of CVDs, associated risk factors, their association with national health expenditures, and an index of critical policy implementation. The Central Europe, Eastern Europe, and Central Asia region face the highest levels of CVD mortality globally. Although CVD mortality levels are generally lower in women than men, this is not true in almost 30% of countries in the North Africa and Middle East and Sub-Saharan regions. Raised blood pressure remains the leading global CVD risk factor, contributing to 10.8 million deaths in 2019. The regions with the highest proportion of countries achieving the maximum score for the WHF Policy Index were South Asia, Central Europe, Eastern Europe, and Central Asia, and the High-Income regions. The Sub-Saharan Africa region had the highest proportion of countries scoring two or less. Policymakers must assess their country's risk factor profile to craft effective strategies for CVD prevention and management. Fundamental strategies such as the implementation of National Tobacco Control Programmes, ensuring the availability of CVD medications, and establishing specialised units within health ministries to tackle non-communicable diseases should be embraced in all countries. Adequate healthcare system funding is equally vital, ensuring reasonable access to care for all communities.",Rethinking ESG‐Financial Performance Nexus Beyond Linearity: A Configurational Analysis,3
41,"Artificial Intelligence–Generated Draft Replies to Patient Inbox Messages In this quality improvement study of an early implementation of generative AI, there was notable adoption, usability, and improvement in assessments of burden and burnout. There was no improvement in time. Further code-to-bedside testing is needed to guide future development and organizational strategy.",Smart sanitary hardware for health monitoring,3
42,"Science with the Australian square kilometre array pathfinder The future of centimetre and metre-wave astronomy lies with the Square Kilometre Array (SKA), a telescope under development by a consortium of 17 countries that will be 50 times more sensitive than any existing radio facility. Most of the key science for the SKA will be addressed through large-area imaging of the Universe at frequencies from a few hundred MHz to a few GHz. The Australian SKA Pathfinder (ASKAP) is a technology demonstrator aimed in the mid-frequency range, and achieves instantaneous wide-area imaging through the development and deployment of phased-array feed systems on parabolic reflectors. The large field-of-view makes ASKAP an unprecedented synoptic telescope that will make substantial advances in SKA key science. ASKAP will be located at the Murchison Radio Observatory in inland Western Australia, one of the most radio-quiet locations on the Earth and one of two sites selected by the international community as a potential location for the SKA. In this paper, we outline an ambitious science program for ASKAP, examining key science such as understanding the evolution, formation and population of galaxies including our own, understanding the magnetic Universe, revealing the transient radio sky and searching for gravitational waves.",Massive runaway star HD 254577: The pre-supernova binary companion to the progenitor of the supernova remnant IC 443,3