In [13]:
import requests
import pandas as pd
import time
from urllib.parse import quote


BASE = "https://api.openalex.org"
MY_INST = "3Ai4405392" # BOUN

def api(endpoint, params):
    return requests.get(f"{BASE}/{endpoint}", params=params).json()

"""
collab_data = api("works", {
    "filter": f"authorships.institutions.id:{MY_INST},publication_year:2020-",
    "group_by": "authorships.institutions.id",
    "per_page": 100,
})["group_by"]

# Get top 5 topics
topics = api("works", {
    "filter": f"authorships.institutions.id:{MY_INST}",
    "group_by": "primary_topic.id",
    "per_page": 5,
})["group_by"]
"""

def fetch_priority_followed_papers_since_2020(output_file="data/priority_followed_data.csv"):
    base_url = f"https://api.openalex.org/works?filter=authorships.institutions.lineage%3Ai97018004%7Ci136199984%7Ci95457486%7Ci1291425158%7Ci4210090411%7Ci27837315%7Ci63966007%2Ctype%3Aarticle%2Cpublication_year%3A2020-"
    all_papers = []
    page = 1
    
    print("Starting to fetch priority followed papers since 2020...")
    
    while True:
        url = f"{base_url}&per_page=200&page={page}"
        response = requests.get(url)
        
        if response.status_code != 200:
            print(f"Error at page {page}: {response.status_code}")
            break
        
        data = response.json()
        results = data.get('results', [])
        
        if not results:
            break
        
        for work in results:
            all_papers.append(work)
            
        print(f"Page {page} fetched. Total papers: {len(all_papers)}")

        if len(results) < 200:
            break
        
        page += 1
        time.sleep(0.1)

    df = pd.DataFrame(all_papers)
    df.to_csv(output_file, index=False, encoding="utf-8")
    print(f"\nCompleted! Total {len(df)} papers saved to {output_file}")

            
def fetch_all_boun_papers(output_file="data/boun_corpus.csv"):
    base_url = f"https://api.openalex.org/works?filter=type%3Aarticle%2Cpublication_year%3A2020-%2Cauthorships.institutions.lineage%{MY_INST}"
    
    all_papers = []
    page = 1
    
    print("Starting to fetch BOUN corpus...")
    
    while True:
        url = f"{base_url}&per_page=200&page={page}"
        response = requests.get(url)
        
        if response.status_code != 200:
            print(f"Error at page {page}: {response.status_code}")
            break
            
        data = response.json()
        results = data.get('results', [])
        
        if not results:
            break
            
        for work in results:
            all_papers.append(work)
            
        print(f"Page {page} fetched. Total papers: {len(all_papers)}")
        
        if len(results) < 200:
            break
        
        page += 1
        time.sleep(0.1)

    df = pd.DataFrame(all_papers)
    df.to_csv(output_file, index=False, encoding="utf-8")
    print(f"\nCompleted! Total {len(df)} papers saved to {output_file}")

# if __name__ == "__main__":
    # fetch_all_boun_papers("data/boun_corpus_since_2020.csv")
    # fetch_priority_followed_papers_since_2020("data/priority_followed_data_since_2020.csv")

In [14]:
from src.preprocessing import process_papers

boun_since_2020 = process_papers("data/boun_corpus_since_2020.csv", "boun")

Loaded 5,038 papers from data/boun_corpus_since_2020.csv
After English filter: 4,608 papers

In [15]:
boun_since_2020

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,...,abstract_inverted_index,counts_by_year,updated_date,created_date,abstract_raw,abstract,abstract_word_count,abstract_keywords,word_frequency,concepts_array
5037,https://openalex.org/W7134201305,https://doi.org/10.17275/per.26.24.13.2,Investigation of Social and Cultural Informal ...,Investigation of Social and Cultural Informal ...,2026,2026-03-08,{'openalex': 'https://openalex.org/W7134201305...,en,"{'id': 'doi:10.17275/per.26.24.13.2', 'is_oa':...",article,...,"{'This': [0], 'study': [1], 'aims': [2], 'to':...",[],2026-03-10T16:38:18.471706,2026-03-09T00:00:00,This study aims to investigate the social and ...,This study aims to investigate the social and ...,252.0,"[students, were, preferences, activities, cult...","{'this': 1, 'study': 1, 'aims': 1, 'investigat...","[Girl, Psychology, Affect (linguistics), Test ..."
4933,https://openalex.org/W7125368247,https://doi.org/10.1007/s10857-025-09739-6,How can teachers learn to teach effectively an...,How can teachers learn to teach effectively an...,2026,2026-01-22,{'openalex': 'https://openalex.org/W7125368247...,en,"{'id': 'doi:10.1007/s10857-025-09739-6', 'is_o...",article,...,None,[],2026-01-26T23:06:41.788003,2026-01-23T00:00:00,NaN,NaN,NaN,None,None,"[Philosophy of education, Mathematics educatio..."
4934,https://openalex.org/W7125377449,https://doi.org/10.1002/bse.70489,Rethinking ESG‐Financial Performance Nexus Bey...,Rethinking ESG‐Financial Performance Nexus Bey...,2026,2026-01-21,{'openalex': 'https://openalex.org/W7125377449...,en,"{'id': 'doi:10.1002/bse.70489', 'is_oa': False...",article,...,"{'ABSTRACT': [0], 'Pressures': [1], 'to': [2, ...",[],2026-03-06T13:50:29.536080,2026-01-23T00:00:00,ABSTRACT Pressures to reconcile both sustainab...,Pressures to reconcile both sustainability com...,137.0,"[financial, esgp, firms, performance, scores, ...","{'abstract': 1, 'pressures': 1, 'reconcile': 1...","[Nexus (standard), Corporate governance, Quali..."
4935,https://openalex.org/W7125416384,https://doi.org/10.1080/00368121.2026.2615961,Computational thinking meets robotics: using m...,Computational thinking meets robotics: using m...,2026,2026-01-21,{'openalex': 'https://openalex.org/W7125416384...,en,"{'id': 'doi:10.1080/00368121.2026.2615961', 'i...",article,...,None,[],2026-01-23T23:24:52.574035,2026-01-23T00:00:00,NaN,NaN,NaN,None,None,"[Mathematics education, Kinematics, Computatio..."
4936,https://openalex.org/W7125475576,https://doi.org/10.1051/0004-6361/202556086,Massive runaway star HD 254577: The pre-supern...,Massive runaway star HD 254577: The pre-supern...,2026,2026-01-21,{'openalex': 'https://openalex.org/W7125475576...,en,"{'id': 'doi:10.1051/0004-6361/202556086', 'is_...",article,...,"{'Aims.': [0], 'The': [1, 212, 317], 'secondar...",[],2026-03-10T16:38:18.471706,2026-01-24T00:00:00,Aims. The secondaries of massive binary system...,Aims. The secondaries of massive binary system...,356.0,"[star, runaway, binary, progenitor, massive, s...","{'aims': 1, 'the': 27, 'secondaries': 1, 'mass...","[Physics, Astrophysics, Neutron star, Supernov..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,https://openalex.org/W3012378318,https://doi.org/10.1007/s10915-020-01189-x,Galerkin Boundary Element Methods for High-Fre...,Galerkin Boundary Element Methods for High-Fre...,2020,2020-03-16,{'openalex': 'https://openalex.org/W3012378318...,en,"{'id': 'doi:10.1007/s10915-020-01189-x', 'is_o...",article,...,None,"[{'year': 2025, 'cited_by_count': 8}, {'year':...",2025-11-06T03:46:38.306776,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Mathematics, Galerkin method, Boundary (topol..."
916,https://openalex.org/W3011218215,https://doi.org/10.1016/j.cep.2020.107914,Strategies for improving CO2 utilization in mi...,Strategies for improving CO2 utilization in mi...,2020,2020-03-19,{'openalex': 'https://openalex.org/W3011218215...,en,"{'id': 'doi:10.1016/j.cep.2020.107914', 'is_oa...",article,...,None,"[{'year': 2026, 'cited_by_count': 1}, {'year':...",2025-11-06T03:46:38.306776,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Syngas, Dimethyl ether, Microreactor, Methano..."
915,https://openalex.org/W3000065871,https://doi.org/10.1109/access.2020.2964803,Genetic Algorithm for the Mutual Information-B...,Genetic Algorithm for the Mutual Information-B...,2020,2020-01-01,{'openalex': 'https://openalex.org/W3000065871...,en,"{'id': 'doi:10.1109/access.2020.2964803', 'is_...",article,...,"{'Filters': [0], 'are': [1, 140], 'the': [2, 5...","[{'year': 2026, 'cited_by_count': 1}, {'year':...",2025-11-06T03:46:38.306776,2025-10-10T00:00:00,Filters are the fastest among the different ty...,Filters are the fastest among the different ty...,215.0,"[feature, selection, algorithm, solutions, inf...","{'filters': 1, 'are': 2, 'the': 5, 'fastest': ...","[Mutual information, Feature selection, Comput..."
3116,https://openalex.org/W3025980162,https://doi.org/10.1128/mra.00309-20,Complete Genome Sequence of <i>Pseudomonas</i>...,Complete Genome Sequence of <i>Pseudomonas</i>...,2020,2020-05-13,{'openalex': 'https://openalex.org/W3025980162...,en,"{'id': 'doi:10.1128/mra.00309-20', 'is_oa': Tr...",article,...,"{'<i>Pseudomonas</i>': [0], 'sp.': [1], 'strai...","[{'year': 2024, 'cited_by_count': 1}, {'year':...",2025-11-06T03:46:38.306776,2020-05-21T00:00:00,<i>Pseudomonas</i> sp. strain BIOMIG1<sup>BAC<...,Pseudomonas sp. strain BIOMIG1BAC is an antibi...,40.0,"[pseudomonas, strain, antibiotic, resistant, g...","{'pseudomonas': 1, 'strain': 1, 'biomig1bac': ...","[Benzalkonium chloride, Whole genome sequencin..."
0,https://openalex.org/W3002058265,https://doi.org/10.1038/s41560-019-0529-5,Consensus statement for stability assessment a...,Consensus statement for stability assessment a...,2020,2020-01-22,{'openalex': 'https://openalex.org/W3002058265...,en,"{'id': 'doi:10.1038/s41560-019-0529-5', 'is_oa...",article,...,None,"[{'year': 2026, 'cited_by_count': 81}, {'year'...",2026-03-10T16:38:18.471706,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Photovoltaics, Statement (logic), Perovskite ..."

In [16]:
priority_papers = process_papers("data/priority_followed_data_since_2020.csv", "priority_followed")

Loaded 10,000 papers from data/priority_followed_data_since_2020.csv
After English filter: 9,946 papers

In [17]:
priority_papers

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,...,abstract_inverted_index,counts_by_year,updated_date,created_date,abstract_raw,abstract,abstract_word_count,abstract_keywords,word_frequency,concepts_array
367,https://openalex.org/W1498342204,https://doi.org/10.1145/3788687,An Introduction to Input/Output Automata,An Introduction to Input/Output Automata,2026,2026-01-27,{'openalex': 'https://openalex.org/W1498342204...,en,"{'id': 'doi:10.1145/3788687', 'is_oa': True, '...",article,...,"{'We': [0, 15], 'describe': [1], 'the': [2, 17...","[{'year': 2024, 'cited_by_count': 2}, {'year':...",2026-03-08T08:50:53.379069,2016-06-24T00:00:00,"We describe the input/output automaton model, ...","We describe the input/output automaton model, ...",44.0,"[model, describe, input, output, automaton, co...","{'describe': 1, 'the': 5, 'inputoutput': 1, 'a...","[Automaton, Computer science, Theoretical comp..."
6720,https://openalex.org/W4406633044,https://doi.org/10.1038/s41562-024-02090-5,Trust in scientists and their role in society ...,Trust in scientists and their role in society ...,2025,2025-01-20,{'openalex': 'https://openalex.org/W4406633044...,en,"{'id': 'doi:10.1038/s41562-024-02090-5', 'is_o...",article,...,"{'Science': [0], 'is': [1, 99], 'crucial': [2]...","[{'year': 2026, 'cited_by_count': 31}, {'year'...",2026-03-10T16:38:18.471706,2025-10-10T00:00:00,Science is crucial for evidence-based decision...,Science is crucial for evidence-based decision...,147.0,"[scientists, trust, evidence, science, decisio...","{'science': 1, 'crucial': 1, 'for': 2, 'eviden...","[Politics, Political science, Affect (linguist..."
6203,https://openalex.org/W4413972333,https://doi.org/10.1177/10507256251363120,2025 American Thyroid Association Management G...,2025 American Thyroid Association Management G...,2025,2025-08-01,{'openalex': 'https://openalex.org/W4413972333...,en,"{'id': 'doi:10.1177/10507256251363120', 'is_oa...",article,...,"{'<b><i>Background:</i></b>': [0], 'Differenti...","[{'year': 2026, 'cited_by_count': 92}, {'year'...",2026-03-10T16:38:18.471706,2025-10-10T00:00:00,<b><i>Background:</i></b> Differentiated thyro...,Background: Differentiated thyroid cancer (DTC...,349.0,"[guidelines, thyroid, cancer, patients, were, ...","{'background': 1, 'differentiated': 1, 'thyroi...","[Thyroid cancer, Medicine, Thyroid, Associatio..."
965,https://openalex.org/W4410611457,https://doi.org/10.70389/pjs.100079,Revised Surgical CAse REport (SCARE) Guideline...,Revised Surgical CAse REport (SCARE) Guideline...,2025,2025-05-22,{'openalex': 'https://openalex.org/W4410611457...,en,"{'id': 'doi:10.70389/pjs.100079', 'is_oa': Tru...",article,...,"{'INTRODUCTION': [0], 'Artificial': [1], 'inte...","[{'year': 2026, 'cited_by_count': 32}, {'year'...",2026-03-08T08:50:53.379069,2025-05-23T00:00:00,INTRODUCTION Artificial intelligence (AI) is r...,INTRODUCTION Artificial intelligence (AI) is r...,228.0,"[scare, consensus, items, update, surgical, ca...","{'introduction': 1, 'artificial': 1, 'intellig...","[Guideline, Psychology, Artificial intelligenc..."
6910,https://openalex.org/W4406426717,https://doi.org/10.1038/s43586-024-00373-9,Perovskite solar cells,Perovskite solar cells,2025,2025-01-16,{'openalex': 'https://openalex.org/W4406426717...,en,"{'id': 'doi:10.1038/s43586-024-00373-9', 'is_o...",article,...,None,"[{'year': 2026, 'cited_by_count': 38}, {'year'...",2026-03-07T16:01:11.037858,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Materials science, Perovskite (structure), Ch..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2788,https://openalex.org/W3011813593,https://doi.org/10.1038/s41467-020-14887-9,Fiber reinforced GelMA hydrogel to induce the ...,Fiber reinforced GelMA hydrogel to induce the ...,2020,2020-03-18,{'openalex': 'https://openalex.org/W3011813593...,en,"{'id': 'doi:10.1038/s41467-020-14887-9', 'is_o...",article,...,None,"[{'year': 2026, 'cited_by_count': 9}, {'year':...",2026-03-09T08:58:05.943551,2020-03-23T00:00:00,NaN,NaN,NaN,None,None,"[Regeneration (biology), Stromal cell, Scaffol..."
2790,https://openalex.org/W3080515170,https://doi.org/10.1016/s2589-7500(20)30160-6,Artificial intelligence in medical imaging: sw...,Artificial intelligence in medical imaging: sw...,2020,2020-08-24,{'openalex': 'https://openalex.org/W3080515170...,en,"{'id': 'doi:10.1016/s2589-7500(20)30160-6', 'i...",article,...,"{'Artificial': [0], 'intelligence': [1], '(AI)...","[{'year': 2026, 'cited_by_count': 5}, {'year':...",2026-01-13T01:12:25.745995,2025-10-10T00:00:00,Artificial intelligence (AI) is a disruptive t...,Artificial intelligence (AI) is a disruptive t...,171.0,"[imaging, detection, might, clinical, performa...","{'artificial': 1, 'intelligence': 1, 'disrupti...","[Overdiagnosis, False positive paradox, Subcli..."
2791,https://openalex.org/W3110610967,https://doi.org/10.1126/science.aaz6063,In vivo Perturb-Seq reveals neuronal and glial...,In vivo Perturb-Seq reveals neuronal and glial...,2020,2020-11-26,{'openalex': 'https://openalex.org/W3110610967...,en,"{'id': 'doi:10.1126/science.aaz6063', 'is_oa':...",article,...,"{'The': [0], 'number': [1], 'of': [2, 69, 103,...","[{'year': 2026, 'cited_by_count': 13}, {'year'...",2026-03-04T09:10:02.777135,2025-10-10T00:00:00,The number of disease risk genes and loci iden...,The number of disease risk genes and loci iden...,134.0,"[cell, risk, genes, identified, genetic, vivo,...","{'the': 4, 'number': 1, 'disease': 1, 'risk': ...","[Biology, Gene, Frameshift mutation, Genetics,..."
2799,https://openalex.org/W2999360818,https://doi.org/10.1126/science.aaz6149,Ultrahigh thermal conductivity in isotope-enri...,Ultrahigh thermal conductivity in isotope-enri...,2020,2020-01-10,{'openalex': 'https://openalex.org/W2999360818...,en,"{'id': 'doi:10.1126/science.aaz6149', 'is_oa':...",article,...,"{'Materials': [0], 'with': [1, 20, 40, 80], 'h...","[{'year': 2026, 'cited_by_count': 15}, {'year'...",2026-03-06T13:50:29.536080,2025-10-10T00:00:00,Materials with high thermal conductivity (κ) a...,Materials with high thermal conductivity (κ) a...,101.0,"[boron, high, thermal, materials, conductivity...","{'materials': 1, 'with': 4, 'high': 1, 'therma...","[Boron nitride, Microelectronics, Boron, Mater..."
5000,https://openalex.org/W3003845413,https://doi.org/10.1038/s41563-019-0597-8,Selective nitrogen adsorption via backbonding ...,Selective nitrogen adsorption via backbonding ...,2020,2020-02-03,{'openalex': 'https://openalex.org/W3003845413...,en,"{'id': 'doi:10.1038/s41563-019-0597-8', 'is_oa...",article,...,None,"[{'year': 2026, 'cited_by_count': 3}, {'year':...",2026-03-10T16:38:18.471706,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Vanadium, Adsorption, Selectivity, Chemistry,..."

In [20]:
# preprocess the fetched works - if there is data/openalex_reference_works_raw.csv
fetched_works = process_papers("data/openalex_reference_works_raw.csv", "openalex_reference_works_raw")

Loaded 1,532 papers from data/openalex_reference_works_raw.csv
After English filter: 1,522 papers

In [21]:
fetched_works

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,...,abstract_inverted_index,counts_by_year,updated_date,created_date,abstract_raw,abstract,abstract_word_count,abstract_keywords,word_frequency,concepts_array
917,https://openalex.org/W4385570519,https://doi.org/10.18653/v1/2023.semeval-1,Proceedings of the The 17th International Work...,Proceedings of the The 17th International Work...,2023.0,2023-01-01,{'openalex': 'https://openalex.org/W4385570519...,en,"{'id': 'doi:10.18653/v1/2023.semeval-1', 'is_o...",paratext,...,"{'Conversational': [0], 'models': [1, 95, 99],...","[{'year': 2025, 'cited_by_count': 17}, {'year'...",2026-01-21T23:30:37.877113,2025-10-10T00:00:00,Conversational models for information seeking ...,Conversational models for information seeking ...,149.0,"[answer, models, information, such, correctnes...","{'conversational': 1, 'models': 1, 'for': 2, '...","[SemEval, Computer science, Natural language p..."
225,https://openalex.org/W4377010360,https://doi.org/10.1001/jamahealthforum.2023.1938,ChatGPT and Physicians’ Malpractice Risk,ChatGPT and Physicians’ Malpractice Risk,2023.0,2023-05-18,{'openalex': 'https://openalex.org/W4377010360...,en,{'id': 'doi:10.1001/jamahealthforum.2023.1938'...,article,...,"{'This': [0], 'JAMA': [1], 'Forum': [2], 'disc...","[{'year': 2026, 'cited_by_count': 5}, {'year':...",2026-03-17T09:09:15.849793,2025-10-10T00:00:00,"This JAMA Forum discusses the possibilities, l...","This JAMA Forum discusses the possibilities, l...",31.0,"[jama, forum, discusses, possibilities, limita...","{'this': 1, 'jama': 1, 'forum': 1, 'discusses'...","[Malpractice, Actuarial science, Risk analysis..."
1452,https://openalex.org/W4385381606,https://doi.org/10.1038/s41746-023-00879-8,The shaky foundations of large language models...,The shaky foundations of large language models...,2023.0,2023-07-29,{'openalex': 'https://openalex.org/W4385381606...,en,"{'id': 'doi:10.1038/s41746-023-00879-8', 'is_o...",review,...,"{'The': [0], 'success': [1], 'of': [2, 40, 128...","[{'year': 2026, 'cited_by_count': 15}, {'year'...",2026-03-26T15:22:09.906841,2025-10-10T00:00:00,The success of foundation models such as ChatG...,The success of foundation models such as ChatG...,143.0,"[models, foundation, data, clinical, trained, ...","{'the': 1, 'success': 1, 'foundation': 3, 'mod...","[Foundation (evidence), Computer science, Narr..."
1314,https://openalex.org/W4316507591,https://doi.org/10.1038/s41589-022-01234-w,Modeling the expansion of virtual screening li...,Modeling the expansion of virtual screening li...,2023.0,2023-01-16,{'openalex': 'https://openalex.org/W4316507591...,en,"{'id': 'doi:10.1038/s41589-022-01234-w', 'is_o...",article,...,None,"[{'year': 2026, 'cited_by_count': 12}, {'year'...",2026-03-24T08:02:53.985720,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Virtual screening, Docking (animal), Chemical..."
1148,https://openalex.org/W4313503621,https://doi.org/10.2139/ssrn.4316615,Large Language Models as Corporate Lobbyists,Large Language Models as Corporate Lobbyists,2023.0,2023-01-01,{'openalex': 'https://openalex.org/W4313503621...,en,"{'id': 'doi:10.2139/ssrn.4316615', 'is_oa': Tr...",article,...,None,"[{'year': 2026, 'cited_by_count': 1}, {'year':...",2026-03-14T08:43:22.919905,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Linguistics, Business, Political science, Law..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1291,https://openalex.org/W1972978214,https://doi.org/10.1214/aoms/1177730491,On a Test of Whether one of Two Random Variabl...,On a Test of Whether one of Two Random Variabl...,1947.0,1947-03-01,{'openalex': 'https://openalex.org/W1972978214...,en,"{'id': 'doi:10.1214/aoms/1177730491', 'is_oa':...",article,...,"{'Let': [0], '$x$': [1], 'and': [2, 14, 27, 80...","[{'year': 2026, 'cited_by_count': 274}, {'year...",2026-03-26T15:22:09.906841,2025-10-10T00:00:00,Let $x$ and $y$ be two random variables with c...,Let $x$ and $y$ be two random variables with c...,191.0,"[distribution, recurrence, relation, statistic...","{'let': 1, 'and': 6, 'two': 1, 'random': 1, 'v...","[Mathematics, Combinatorics, Moment (physics),..."
968,https://openalex.org/W1969089620,https://doi.org/10.1097/00001888-193801000-00007,The Association of American Medical Colleges,The Association of American Medical Colleges,1938.0,1938-01-01,{'openalex': 'https://openalex.org/W1969089620...,en,"{'id': 'doi:10.1097/00001888-193801000-00007',...",article,...,None,"[{'year': 2025, 'cited_by_count': 285}, {'year...",2026-01-08T20:05:33.558190,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Association (psychology), Medical education, ..."
975,https://openalex.org/W4243639737,https://doi.org/10.2307/2276774,"Probable Inference, the Law of Succession, and...","Probable Inference, the Law of Succession, and...",1927.0,1927-06-01,{'openalex': 'https://openalex.org/W4243639737...,en,"{'id': 'doi:10.2307/2276774', 'is_oa': False, ...",article,...,None,"[{'year': 2026, 'cited_by_count': 10}, {'year'...",2026-03-20T23:20:44.827607,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Inference, Ecological succession, Statistical..."
506,https://openalex.org/W1964157254,https://doi.org/10.1126/science.49.1254.51,The American Psychological Association,The American Psychological Association,1919.0,1919-01-10,{'openalex': 'https://openalex.org/W1964157254...,en,"{'id': 'doi:10.1126/science.49.1254.51', 'is_o...",article,...,None,"[{'year': 2026, 'cited_by_count': 1}, {'year':...",2026-02-27T16:54:17.756197,2025-10-10T00:00:00,NaN,NaN,NaN,None,None,"[Association (psychology), Psychology, Psychot..."
1521,https://openalex.org/W1706435611,https://doi.org/10.1080/14786448208628425,XX. <i>On the equilibrium of liquid conducting...,XX. <i>On the equilibrium of liquid conducting...,1882.0,1882-09-01,{'openalex': 'https://openalex.org/W1706435611...,en,"{'id': 'doi:10.1080/14786448208628425', 'is_oa...",article,...,"{'(1882).': [0], 'XX.': [1], 'On': [2], 'the':...","[{'year': 2026, 'cited_by_count': 8}, {'year':...",2026-03-20T23:20:44.827607,2025-10-10T00:00:00,(1882). XX. On the equilibrium of liquid condu...,(1882). XX. On the equilibrium of liquid condu...,29.0,"[equilibrium, liquid, conducting, masses, char...","{'1882': 1, 'the': 1, 'equilibrium': 1, 'liqui...","[Electricity, Physics, Quantum mechanics]"

In [22]:
# print columns of fetched_works
print(fetched_works.columns)

Index(['id', 'doi', 'title', 'display_name', 'publication_year',
       'publication_date', 'ids', 'language', 'primary_location', 'type',
       'indexed_in', 'open_access', 'authorships', 'institutions',
       'countries_distinct_count', 'institutions_distinct_count',
       'corresponding_author_ids', 'corresponding_institution_ids', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_percentile', 'cited_by_percentile_year', 'biblio',
       'is_retracted', 'is_paratext', 'is_xpac', 'primary_topic', 'topics',
       'keywords', 'concepts', 'mesh', 'locations_count', 'locations',
       'best_oa_location', 'sustainable_development_goals', 'awards',
       'funders', 'has_content', 'content_urls', 'referenced_works_count',
       'referenced_works', 'related_works', 'abstract_inverted_index',
       'counts_by_year', 'updated_date', 'created_date', 'abstract_raw',
       'abstract', 'abstract_word_count', 'abstract_keywords',
       'word_frequency', 'concepts_array'],
      dtype='str')